CREATE DATABASE IF NOT EXISTS vulnerable_login;

USE DATABASE vulnerable_login;

CREATE TABLE IF NOT EXISTS files (
    id INT PRIMARY KEY AUTO_INCREMENT,
    fileName VARCHAR(255) NOT NULL,
    fileSize INT NOT NULL,
    uploadDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    uploadedBy VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS comments (
    id INT PRIMARY KEY AUTO_INCREMENT,
    file_id INT NOT NULL,
    commentText TEXT NOT NULL,
    commenter VARCHAR(255) NOT NULL,
    commentDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (file_id) REFERENCES files(id) ON DELETE CASCADE
);